inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-slim
  - rubocop-rspec_rails

Capybara:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.2.0
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
  NewCops: enable

RSpec/NestedGroups:
  Max: 4